#!/bin/bash
# Generated by upload-artifacts.sh
export ARTIFACTS_BUCKET="wpsuite-artifacts"
export S3_PREFIX="wpsuite-flow/1.0.0"
export AWS_REGION="us-east-1"
export APP_NAME="wpsuite-flow"
export GIT_SHA="670de1a"
export ARTIFACT_VERSION="1.0.0"
export TEMPLATE_URL="https://wpsuite-artifacts.s3.us-east-1.amazonaws.com/wpsuite-flow/1.0.0/template.yaml"
